docs_dir: "content"
site_name: pokemon-ace-notes
site_url: https://pomeg-letterbombers.github.io/pokemon-ace-notes/
repo_name: pokemon-ace-notes
repo_url: https://github.com/pomeg-letterbombers/pokemon-ace-notes/
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><span property="dct:title">pokemon-ace-notes</span> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>
nav:
  - "Home": "index.md"
  - "FireRed and LeafGreen":
    - "Getting Started":
      - "frlg-introduction.md"
      - "mail-glitch.md"
      - "Non-Japanese ACE Setup":
        - "frlg-non-jpn-ace/index.md"
        - "Pre-Elite Four Route (HOCK 2.O)": "frlg-non-jpn-pre-e4-route.md"
        - "Post-Elite Four Route": "frlg-non-jpn-post-e4-route.md"
        - "MIMIEN Route": "frlg-non-jpn-mimien-route.md"
        - "NINO/NINA Route": "frlg-non-jpn-nino-nina-route.md"
        - "Other Empty Slot Corruption Routes": "frlg-non-jpn-other-empty-slot-routes.md"
      - "Japanese ACE Setup":
        - "frlg-jpn-ace/index.md"
        - "Main Route": "frlg-jpn-main-route.md"
        - "ニドくん Route": "frlg-jpn-nido-route.md"
    - "Exit Codes":
      - "frlg-box-14-exit.md"
      - "frlg-box-14-exit-biosless.md"
      - "frlg-exit-code-bootstrap.md"
    - "Complex Payloads":
      - "frlg-hex-writer.md"
  - "FAQ": "faq.md"
  - "Technical Documentation":
    - "frlg-hexwriter-setup-explanation.md"
    - "frlg-grab-ace-exit.md"
    - "jpn-frlg-ace-explanation.md"
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - footnotes
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
  font:
    text: Source Sans 3
    code: Source Code Pro
  palette:
    primary: black
plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
  - redirects:
      redirect_maps:
        "frlg/getting-started/introduction.md": "frlg-introduction.md"
        "frlg/getting-started/mail-glitch.md": "mail-glitch.md"
        "frlg/getting-started/non-jpn-ace/index.md": "frlg-non-jpn-ace/index.md"
        "frlg/getting-started/non-jpn-ace/pre-e4-route.md": "frlg-non-jpn-pre-e4-route.md"
        "frlg/getting-started/non-jpn-ace/post-e4-route.md": "frlg-non-jpn-post-e4-route.md"
        "frlg/getting-started/non-jpn-ace/mimien-route.md": "frlg-non-jpn-mimien-route.md"
        "frlg/getting-started/non-jpn-ace/nino-nina-route.md": "frlg-non-jpn-nino-nina-route.md"
        "frlg/getting-started/non-jpn-ace/other-empty-slot-routes.md": "frlg-non-jpn-other-empty-slot-routes.md"
        "frlg/getting-started/jpn-ace/index.md": "frlg-jpn-ace/index.md"
        "frlg/getting-started/jpn-ace/main-route.md": "frlg-jpn-main-route.md"
        "frlg/getting-started/jpn-ace/nido-kun-route.md": "frlg-jpn-nido-route.md"
        "frlg/exit-codes/box-14-exit.md": "frlg-box-14-exit.md"
        "frlg/exit-codes/old-box-14-exit.md": "frlg-box-14-exit-biosless.md"
        "frlg/exit-codes/exit-code-bootstrap.md": "frlg-exit-code-bootstrap.md"
        "frlg/complex-payloads/hex-writer.md": "frlg-hex-writer.md"
        "technical-documentation/writing-hexwriter.md": "frlg-hexwriter-setup-explanation.md"
        "technical-documentation/grab-ace-exit.md": "frlg-grab-ace-exit.md"
        "technical-documentation/getting-ace-in-jpn-frlg.md": "jpn-frlg-ace-explanation.md"
